"use strict";

// UI-only translations. Documents, answers and editable values stay unchanged.
const UI_EN = Object.fromEntries(`
Bỏ qua điều hướng|Skip navigation
BlueStudy — trang chủ|BlueStudy — home
MỘT CUỐN VỞ. VẠN ĐIỀU HAY.|ONE NOTEBOOK. ENDLESS DISCOVERIES.
MỤC LỤC|CONTENTS
Điều hướng chính|Main navigation
Sơ đồ bài học|Learning map
Đề thi & ôn tập|Exams & revision
Lộ trình học|Learning path
Tủ tài liệu|Library
Sổ tiến bộ|Progress
NHỮNG CUỐN VỞ|YOUR NOTEBOOKS
Thêm cuốn vở|Add notebook
Chưa có cuốn vở nào.|No notebooks yet.
GHI CHÚ NHỎ|A LITTLE NOTE
Không cần biết tất cả.|You do not need to know everything.
Chỉ cần hiểu thêm|Just learn a little more
một chút mỗi ngày.|every day.
— cùng bạn, BlueStudy ♡|— with you, BlueStudy ♡
Góc học tập của bạn|Your study space
Khám phá một cuốn vở mẫu|Explore a sample notebook
Góc học tập|Study space
Hồ sơ học tập|Learning profile
Hướng dẫn sử dụng|Help
◦ Vở mẫu|◦ Sample notebook
Viết tiếp sự tò mò của bạn.|Keep your curiosity growing.
Học từng chút. Hiểu thật lâu.|Small steps. Lasting understanding.
MỞ TRANG ĐẦU TIÊN|OPEN YOUR FIRST PAGE
Đóng hướng dẫn|Close help
Một cuốn vở, nhiều cách học.|One notebook, many ways to learn.
Thêm ảnh, PDF hoặc ghi chú vào|Add images, PDFs or notes to your
Kiểm tra văn bản, chọn đoạn học và tạo bộ ôn tập.|Review the text, select a passage and create a study pack.
Bấm một tờ ghi chú trên sơ đồ để đọc, hỏi và luyện tập.|Select a note on the map to read, ask and practise.
Xem các câu cần ôn trong|Find questions to revisit in
Góc học tập tự lưu trên máy này. Thêm tài liệu của bạn để bắt đầu.|Your study space is saved on this device. Add a document to get started.
Hôm nay, mình học gì?|What shall we learn today?
Biến ghi chú của bạn thành những bước học nhỏ, dễ hiểu.|Turn your notes into small, manageable learning steps.
01 / BẮT ĐẦU TỪ TÀI LIỆU CỦA BẠN|01 / START WITH YOUR MATERIALS
Ghi chú lộn xộn? Để BlueStudy giúp bạn.|Messy notes? Let BlueStudy help.
Thêm ảnh, PDF hoặc dán ghi chú. Kiểm tra nội dung rồi tạo bộ ôn tập của riêng mình.|Upload an image or PDF, or paste your notes. Review the text and create your own study pack.
Tên ghi chú|Note title
Nội dung (tối đa 2.400 ký tự)|Content (up to 2,400 characters)
Lưu ghi chú|Save note
Tải ảnh hoặc PDF|Upload an image or PDF
PNG, JPG, PDF · tối đa 10 MB, 20 trang|PNG, JPG, PDF · up to 10 MB, 20 pages
Chọn tài liệu|Choose a document
Tải lên|Upload
Hãy chọn một tài liệu.|Please choose a document.
Thư viện của bạn|Your library
GHI CHÚ|NOTE
TÀI LIỆU|DOCUMENT
Mở tài liệu →|Open document →
Tài liệu đầu tiên của bạn sẽ xuất hiện ở đây.|Your first document will appear here.
Cần kiểm tra|Needs review
Sẵn sàng học|Ready to study
Đang xử lý|Processing
Xử lý chưa thành công|Processing failed
Tải bản gốc|Download original
Mở tài liệu gốc|Open original document
Chuyển thành đề thi có cấu trúc|Convert to a structured exam
Bạn có thể quay lại thư viện trong lúc BlueStudy đọc tài liệu.|You can return to the library while BlueStudy reads your document.
Không đọc được tài liệu. Bạn có thể thử lại hoặc nhập văn bản bên dưới.|Unable to read this document. Try again or enter the text below.
Thử đọc lại|Retry extraction
Kiểm tra và sửa văn bản trích xuất|Review and edit extracted text
Lưu và xác nhận nội dung|Save and confirm content
Văn bản trích xuất|Extracted text
Bắt đầu từ ký tự|Start character
Kết thúc tại ký tự (đoạn học tối đa 2.400 ký tự)|End character (up to 2,400 characters)
Tạo bộ ôn tập|Create study pack
Xóa tài liệu|Delete document
Xóa tài liệu cùng các bộ học và điểm liên quan?|Delete this document and its study packs and scores?
Hãy lưu và xác nhận phần văn bản vừa sửa trước khi học.|Save and confirm your changes before studying.
Chọn đoạn hợp lệ từ 1 đến 2.400 ký tự.|Select a passage of 1 to 2,400 characters.
Hãy nhập văn bản nguồn.|Please enter the source text.
Tài liệu nguồn|Source document
Chủ đề học (bạn tự xác nhận)|Topic (confirm your selection)
Chưa xác định|Not selected
Lưu chủ đề|Save topic
Nguồn chủ đề: HEID / Global Success|Topic source: HEID / Global Success
Đã lưu lựa chọn chủ đề của bạn.|Your topic selection has been saved.
Những câu cần ôn lại|Questions to revisit
Mở bộ học|Open study pack
Chưa đủ lượt để nhận xét|Not enough attempts yet
Nên dành thêm thời gian ôn|Needs more practice
Kết quả luyện tập tốt|Doing well
Tiếp tục luyện tập|Keep practising
Tạo bộ ôn tập mới|Create a new study pack
BlueStudy đang chuẩn bị nội dung. Bạn có thể quay lại phiên học sau.|BlueStudy is preparing your materials. You can return to this session later.
Tác vụ vẫn đang xử lý. Mở lại phiên học sau.|Still processing. Return to this session later.
Nội dung AI chưa được giáo viên kiểm duyệt. Hãy đối chiếu với tài liệu gốc.|AI content has not been reviewed by a teacher. Check it against the original source.
Bộ học này được tạo bằng mô hình local dự phòng.|This study pack was generated by the local fallback model.
Phiên học đã lưu|Saved study sessions
Mở lại phiên học và bộ ôn tập đã lưu.|Return to your saved sessions and study packs.
Chưa có phiên học. Hãy bắt đầu từ thư viện.|No study sessions yet. Start in the library.
Tiếp tục học|Continue learning
Điểm luyện tập|Practice scores
Điểm tự luyện giúp bạn nhìn lại quá trình, không thay thế đánh giá của giáo viên.|Practice scores help track your learning and do not replace a teacher's assessment.
Ôn lại bộ học|Review study pack
Xóa lịch sử điểm|Delete score history
Xóa toàn bộ lịch sử điểm của bạn?|Delete all your score history?
Cách học phù hợp với bạn|Learning your way
Bạn có thể thay đổi mức hỗ trợ ngôn ngữ bất cứ lúc nào.|You can change your language support level at any time.
Tên hiển thị|Display name
Mức hỗ trợ tiếng Anh|English support level
Giải thích kỹ bằng tiếng Việt|Detailed explanations in Vietnamese
Cơ bản|Basic
Tự tin với tiếng Anh|Confident in English
Hoạt động bạn thích|Preferred activity
Đọc ghi chú|Read notes
Ôn flashcard|Review flashcards
Làm quiz|Take a quiz
Lưu hồ sơ|Save profile
Đã lưu hồ sơ học tập.|Your learning profile has been saved.
Giữ nguyên đề gốc · Phân loại từng câu · Ôn theo kết quả làm bài|Preserve the original exam · Classify each question · Review based on your results
PDF → đề thi có cấu trúc|PDF → structured exam
Tải PDF tối đa 10 MB, 20 trang. Giữ câu hỏi, lựa chọn A–D và đoạn đọc dùng chung; không tạo câu hỏi về mã đề hay thời gian thi.|Upload a PDF up to 10 MB and 20 pages. Preserve questions, A–D options and shared passages; exclude administrative details from practice questions.
Chọn PDF đề thi|Choose an exam PDF
Chuyển thành đề thi|Convert to exam
Hãy chọn PDF đề thi.|Please choose an exam PDF.
Đề thi của bạn|Your exams
Mở đề thi|Open exam
Chưa có đề thi. Hãy tải PDF để bắt đầu.|No exams yet. Upload a PDF to get started.
Đang mở đề thi…|Opening exam…
Đang trích xuất PDF|Extracting PDF
AI đang phân loại câu hỏi|AI is classifying questions
Sẵn sàng luyện tập|Ready to practise
Cần kiểm tra câu bị thiếu|Review missing questions
Chưa xử lý được|Unable to process
← Danh sách đề thi|← All exams
Đáp án do AI đề xuất, chưa có đáp án chính thức được đối chiếu. Điểm và gợi ý ôn tập chỉ tạm tính; câu AI chưa xác định được sẽ không tính điểm.|Answers are suggested by AI and have not been checked against an official answer key. Scores and revision advice are provisional; questions without an AI answer are not graded.
03 · Làm bài để nhận gợi ý ôn tập|03 · Take the exam to get revision advice
Hoàn tất|Complete
Đã chấm; chưa có gợi ý AI|Graded; AI advice unavailable
Đang chuẩn bị gợi ý|Preparing advice
Cần kiểm tra nội dung trích xuất trước khi chấm bài; hệ thống không tự bịa câu bị thiếu.|Review the extracted content before grading; missing questions will not be invented.
Mở tài liệu để kiểm tra|Open document for review
Thử chuyển đổi lại|Retry conversion
Tải đề có cấu trúc (JSON)|Download structured exam (JSON)
Kỹ năng|Skill
Đúng / đã chấm|Correct / graded
Câu cần ôn|Questions to review
AI hỗ trợ ôn tập|AI revision support
Chưa tạo được nhận xét AI. Bạn vẫn có thể ôn theo bảng kỹ năng và giải thích từng câu.|AI feedback is unavailable. You can still review the skill breakdown and question explanations.
AI đang phân tích kết quả để gợi ý ôn tập…|AI is analysing your results to suggest revision…
Làm lại đề|Retake exam
Lịch sử làm bài|Attempt history
Chọn kết quả đã lưu|Select a saved result
Nộp bài và phân tích kết quả|Submit and analyse results
Đoạn đọc / hướng dẫn dùng chung|Shared passage / instructions
Chưa xác định được đáp án — không tính điểm.|Answer uncertain — not graded.
✓ Khớp đáp án AI đề xuất|✓ Matches the AI-suggested answer
✕ Chưa khớp đáp án AI đề xuất|✕ Does not match the AI-suggested answer
Bạn còn câu chưa chọn. Nộp bài với các câu đó để trống?|Some questions are unanswered. Submit with those questions left blank?
Chưa cập nhật được trạng thái. Hệ thống sẽ thử lại.|Unable to refresh the status. Retrying automatically.
HỎI MỘT ĐIỀU · HIỂU THÊM MỘT CHÚT|ASK A QUESTION · LEARN A LITTLE MORE
Chat cùng BlueStudy|Chat with BlueStudy
Hỏi bài, gửi ghi chú hoặc cùng chuẩn bị cho buổi học tiếp theo.|Ask a question, share notes or prepare for your next lesson.
＋ Chat mới|＋ New chat
✦ Hỏi bài trực tiếp, đính kèm ảnh/PDF hoặc tạo tài liệu ôn tập từ ghi chú của bạn.|✦ Ask questions, attach images/PDFs or create study materials from your notes.
Cuộc trò chuyện với BlueStudy|Conversation with BlueStudy
Trạng thái xử lý|Processing status
Trợ lý học tập dành cho học sinh Việt Nam|An AI study companion for Vietnamese students
Lịch sử trò chuyện|Chat history
Cuộc trò chuyện mới|New conversation
Cuộc trò chuyện hiện tại|Current conversation
Tin nhắn|Messages
Chọn ảnh hoặc PDF để đính kèm|Choose an image or PDF to attach
Đính kèm ảnh hoặc PDF|Attach an image or PDF
Hỏi bất cứ điều gì, hoặc gửi ghi chú, ảnh/PDF…|Ask anything, or send notes, images/PDFs…
Tin nhắn cho BlueStudy|Message BlueStudy
Gửi ↑|Send ↑
Enter để gửi · Shift + Enter để xuống dòng · AI có thể mắc lỗi|Enter to send · Shift + Enter for a new line · AI can make mistakes
Hôm nay, bạn muốn hiểu điều gì?|What would you like to understand today?
Bạn có thể hỏi ngay mà không cần tải tài liệu. Nếu có ghi chú, hãy gửi ảnh hoặc PDF để mình cùng đọc nhé.|Ask a question without uploading anything. If you have notes, share an image or PDF and we can read it together.
Giải thích since và for|Explain since and for
Giúp mình lên kế hoạch ôn tập|Help me plan my revision
Cách học từ vựng hiệu quả|How to learn vocabulary effectively
Chưa trả lời được lúc này. Bạn có thể gửi lại câu hỏi.|Unable to answer right now. Please try sending your question again.
Đã nhận câu hỏi · đang chờ hoặc xử lý…|Question received · queued or processing…
● THEO DÕI PHIÊN HỌC|● LIVE SESSION MONITOR
BlueStudy đang làm gì?|What is BlueStudy doing?
Trạng thái lấy từ tác vụ đang lưu trên hệ thống.|Live status from the tasks saved in the system.
3 bước tạo quiz|3 steps to create a quiz
Tiến độ tạo quiz|Quiz generation progress
KẾT QUẢ|RESULT
Đã chấm trên máy chủ và lưu vào lịch sử chat.|Graded on the server and saved in chat history.
01 / NGUỒN HỌC|01 / STUDY SOURCE
Tài liệu đính kèm|Attachment
Đã chọn đoạn nguồn|Source passage selected
Trò chuyện tự do|Open conversation
Gửi trực tiếp cho Qwen-VL local cùng câu hỏi của bạn.|Sent directly to local Qwen-VL with your question.
Bạn có thể hỏi mà không cần tài liệu.|You can ask without attaching a document.
02 / TRỢ LÝ HỘI THOẠI|02 / CHAT ASSISTANT
Đang chờ / xử lý|Queued / processing
Đã trả lời|Answered
Chưa hoàn tất|Incomplete
Sẵn sàng lắng nghe|Ready to listen
Câu hỏi đã vào hàng đợi. Bạn có thể mở lại cuộc trò chuyện sau.|Your question is queued. You can return to this conversation later.
Không có câu trả lời hoàn chỉnh. Hãy thử gửi lại.|No complete answer was received. Please try again.
Câu trả lời đã được nhận và lưu.|The answer has been received and saved.
Gửi câu hỏi để bắt đầu.|Send a question to get started.
03 / LỊCH SỬ|03 / HISTORY
Lưu theo tài khoản|Saved to your account
Lịch sử sẽ xuất hiện sau tin nhắn đầu tiên.|History will appear after your first message.
Mô hình trả lời|Response model
Xóa cuộc trò chuyện|Delete conversation
Xóa cuộc trò chuyện và toàn bộ tin nhắn trong đó?|Delete this conversation and all its messages?
Qwen-VL sẽ đọc trực tiếp ảnh khi bạn bấm Gửi|Qwen-VL will read the image when you press Send
Bỏ ảnh|Remove image
Bỏ đính kèm|Remove attachment
Đang dùng đoạn nguồn đã xác nhận|Using your confirmed source passage
✦ Tạo bộ ôn tập|✦ Create study pack
✦ Tạo quiz trắc nghiệm|✦ Create multiple-choice quiz
Mở sơ đồ bài học ↗|Open learning map ↗
Tạo tóm tắt, flashcard và quiz từ đoạn nguồn đã xác nhận.|Create a summary, flashcards and quiz from the confirmed passage.
Đã gửi yêu cầu tạo bộ ôn tập.|Study pack requested.
Hãy viết câu hỏi của bạn.|Please enter your question.
Tệp tối đa 10 MB.|Maximum file size: 10 MB.
Ảnh đã sẵn sàng. Nhập câu hỏi rồi bấm Gửi; Qwen-VL sẽ xem ảnh và trả lời ngay trong chat.|Image ready. Enter a question and press Send; Qwen-VL will read the image and reply in chat.
PDF đã lưu. Hãy kiểm tra văn bản trích xuất để dùng làm nguồn.|PDF saved. Review the extracted text to use it as a source.
TÀI LIỆU ĐÍNH KÈM|ATTACHMENT
Kiểm tra tài liệu đính kèm|Review attachment
Kiểm tra trước khi cùng học|Review before studying
Sửa những chỗ nhận dạng chưa đúng. Sau đó chọn đoạn tối đa 2.400 ký tự để dùng trong cuộc trò chuyện.|Correct any extraction errors, then select up to 2,400 characters to use in the conversation.
Ký tự bắt đầu|Start character
Ký tự kết thúc|End character
Xác nhận và dùng trong chat|Confirm and use in chat
Để sau|Later
Nguồn đã được xác nhận. Các tin nhắn mới sẽ dùng đoạn vừa chọn.|Source confirmed. New messages will use the selected passage.
Chờ BlueStudy trả lời trước khi tạo bộ ôn tập.|Wait for BlueStudy to reply before creating a study pack.
Chờ câu trả lời hiện tại trước khi đổi tài liệu.|Wait for the current answer before changing documents.
Chưa cập nhật được trạng thái. Lịch sử đã nhận vẫn được lưu; hệ thống sẽ thử lại.|Unable to refresh the status. Received messages remain saved; retrying automatically.
Quiz trắc nghiệm|Multiple-choice quiz
QUICK QUIZ · TỰ KIỂM TRA|QUICK QUIZ · CHECK YOUR UNDERSTANDING
Nộp bài|Submit answers
✓ Đúng|✓ Correct
✕ Đã chọn|✕ Your choice
Đã lưu kết quả. Bạn có thể tạo quiz mới để luyện tiếp.|Results saved. Create a new quiz to keep practising.
SỔ TAY HỌC TẬP / BlueStudy|LEARNING NOTEBOOK / BlueStudy
Cuốn vở tri thức của bạn|Your notebook of knowledge
Ghi lại điều hay. Nối những ý tưởng. Hiểu thêm mỗi ngày.|Capture discoveries. Connect ideas. Learn a little every day.
Mở cuốn vở mới|New notebook
Trang kiến thức|Learning pages
Hoạt động học|Learning activities
Lượt tự kiểm tra|Practice attempts
Điểm trung bình|Average score
tài liệu|documents
trang trong vở|pages in your notebook
lượt đã lưu|saved attempts
chưa có điểm|no scores yet
Chưa có điểm|No scores yet
01 / KẾT NỐI Ý TƯỞNG|01 / CONNECT IDEAS
VỞ MẪU|SAMPLE
☷ Danh sách|☷ List
⌘ Sơ đồ|⌘ Map
⌕  Tìm trong bài học…|⌕  Search this lesson…
Tìm trong sơ đồ|Search the map
Thu nhỏ sơ đồ|Zoom out
Phóng to sơ đồ|Zoom in
Mức thu phóng|Zoom level
Đặt lại sơ đồ|Reset map
Đổi cách xem sơ đồ|Change map view
Mỗi ý tưởng đều có một sợi dây kết nối…|Every idea has a connection…
• bắt đầu từ đây|• start here
• chạm để khám phá|• tap to explore
┄┄ Cùng một đoạn nguồn|┄┄ Shared source passage
── Trang đang đọc|── Current page
▷ Khám phá từng bước|▷ Explore step by step
Ⅱ Tạm dừng|Ⅱ Pause
↪ Trang tiếp|↪ Next page
⌕ Chọn một ghi chú|⌕ Select a note
MỘT VIỆC NHỎ HÔM NAY|ONE SMALL STEP TODAY
Đọc một trang, thử 5 câu hỏi, rồi tiến thêm một chút.|Read a page, try five questions and take another small step.
Học tiếp →|Continue →
Lật thêm vài trang|Explore more pages
Có thể bạn cũng muốn biết|You might also like
GHI CHÉP BÀI HỌC|LESSON NOTES
Tiếng Anh 9|Grade 9 English
◦ Từ tài liệu của bạn|◦ From your document
Bài học|Lesson
Hỏi BlueStudy|Ask BlueStudy
Hỏi BlueStudy|Ask BlueStudy
Luyện tập|Practice
Ý CHÍNH CẦN NHỚ|KEY IDEAS
Nội dung trang học|Lesson content
MỘT CÂU HỎI NHỎ|A QUICK QUESTION
Lật thẻ · xem lời giải|Flip card · see explanation
Gấp lại · tự nhớ thử|Hide answer · try to recall
Đọc đoạn nguồn tiếng Anh|Read the English source
CÙNG GỠ RỐI MỘT CHÚT|LET'S WORK IT OUT
Bạn muốn hiểu thêm điều gì?|What would you like to explore?
Chỗ nào khiến bạn băn khoăn? Mình sẽ cùng nhìn lại đoạn nguồn.|What feels unclear? Let's look at the source together.
Đưa câu hỏi vào ô nhập|Use this question
TỰ KIỂM TRA · 5 CÂU NHỎ|SELF CHECK · 5 QUESTIONS
QUIZ MẪU · 5 CÂU NHỎ|SAMPLE QUIZ · 5 QUESTIONS
Nộp bài và xem giải thích|Submit and see explanations
Bạn cần trả lời đủ 5 câu.|Please answer all five questions.
KẾT QUẢ THỬ · KHÔNG LƯU ĐIỂM|SAMPLE RESULTS · SCORES NOT SAVED
ĐÃ LƯU VÀO SỔ TIẾN BỘ|SAVED TO YOUR PROGRESS
Luyện lại một lượt|Practise again
Chính xác|Correct
Cùng ôn lại|Let's review
← Bài trước|← Previous lesson
Bài tiếp →|Next lesson →
Câu tiếp →|Next question →
TRANG GIẤY ĐANG CHỜ BẠN|YOUR NEXT PAGE AWAITS
Cuốn vở đầu tiên đang chờ bạn ở Tủ tài liệu.|Your first notebook is waiting in the Library.
Các trang kiến thức sẽ xuất hiện sau khi tạo bộ ôn tập.|Learning pages will appear once you create a study pack.
Tạo bộ ôn tập để bắt đầu tự kiểm tra.|Create a study pack to start practising.
Đoạn nguồn đã sẵn sàng. Tạo bộ ôn tập để có ghi chú rõ ràng, thẻ ghi nhớ và 5 câu tự kiểm tra.|Your source is ready. Create clear notes, flashcards and a five-question quiz.
Vở mẫu · thử thoải mái, không lưu vào hồ sơ.|Sample notebook · explore freely without changing your profile.
Vở mẫu biên soạn sẵn · điểm luyện tập không được lưu.|Prepared sample notebook · practice scores are not saved.
Lộ trình cho những bước nhỏ|A path of small steps
Mỗi trang học là một bước. Không cần vội, chỉ cần bắt đầu.|Every page is a step. Take your time and begin.
Gom những điều muốn học|Gather what you want to learn
Tải ảnh, PDF hoặc dán ghi chú vào cuốn vở của bạn.|Upload images, PDFs or paste notes into your notebook.
Mở tủ tài liệu|Open library
Biến ghi chú thành những trang học|Turn notes into learning pages
Chọn một trang trên sơ đồ. Đọc nguồn và thử tự trả lời trước khi lật thẻ.|Select a page on the map. Read the source and try answering before flipping the card.
Mở sơ đồ|Open map
Một lượt tự kiểm tra|Check your understanding
Làm 5 câu hỏi. Sai ở đâu, mình cùng quay lại trang đó.|Try five questions. Revisit the pages you found difficult.
Bắt đầu học →|Start learning →
Nhìn lại hành trình|Look back at your journey
Xem điểm đã lưu và những câu cần ôn lại.|View saved scores and questions to revisit.
Xem sổ tiến bộ|View progress
Những trang đang đọc dở|Pick up where you left off
Phiên học gần đây|Recent sessions
Tiếp tục phiên học|Continue session
Tiếp tục bước nhỏ của bạn|Take your next small step
Mỗi bước nhỏ đều đáng ghi nhận.|Every small step counts.
Chủ đề, nguồn & bộ học đã lưu|Saved topics, sources and study packs
100 LƯỢT LÀM BÀI GẦN NHẤT|100 MOST RECENT ATTEMPTS
◉ Hoạt động|◉ Active
● Cuốn vở của bạn|● Your notebook
● Góc học tập|● Study space
◦ Vở mẫu · trải nghiệm|◦ Sample · explore
Kiểm tra văn bản|Review text
Không tải được bản gốc.|Unable to download the original.
Phiên học đã hết hạn. Tải lại trang để tiếp tục.|Your session has expired. Reload to continue.
Không mở được góc học tập. Kiểm tra API và tài khoản mặc định trên máy.|Unable to open your study space. Check the API and local account settings.
Đăng nhập|Sign in
Đăng xuất|Sign out
Chưa đăng nhập|Not signed in
Đăng nhập để bắt đầu|Sign in to start
Đăng nhập để trò chuyện với BlueStudy…|Sign in to chat with BlueStudy…
◦ Đăng nhập để chat|◦ Sign in to chat
Ảnh sắp gửi|Image to send
Ảnh đã gửi cho Qwen-VL|Image sent to Qwen-VL
Ngữ pháp|Grammar
Từ vựng|Vocabulary
Đọc hiểu|Reading comprehension
Liên kết văn bản|Text cohesion
Liên kết và sắp xếp văn bản|Text cohesion and ordering
Từ loại|Word forms
Trật tự từ|Word order
Dạng động từ|Verb forms
Giới từ|Prepositions
Cụm từ|Collocations
Từ nối|Connectors
Từ hạn định|Determiners
Từ vựng trong ngữ cảnh|Vocabulary in context
Cấu trúc câu|Sentence structure
Sắp xếp câu|Sentence ordering
Thông tin chi tiết|Reading for detail
Ý chính|Main idea
Suy luận|Inference
Từ quy chiếu|Reference words
Diễn đạt tương đương|Paraphrasing
Chèn câu|Sentence insertion
Cần phân loại thêm|Needs further classification
Chọn đáp án theo đoạn đọc/hướng dẫn phía trên.|Choose an answer using the passage/instructions above.
Tình nguyện viên|Volunteers
Ai giúp đỡ hàng xóm lớn tuổi?|Who helps older neighbours?
Ai giúp đỡ những người hàng xóm lớn tuổi?|Who helps older neighbours?
Các tình nguyện viên — volunteers.|Volunteers help older neighbours.
Thư viện|Library
Thư viện mang đến điều gì cho cộng đồng?|What does the library offer the community?
Thư viện cho mượn sách miễn phí.|The library lends books for free.
Lính cứu hỏa|Firefighters
A firefighter làm công việc gì?|What does a firefighter do?
Lính cứu hỏa dập lửa. Cụm động từ: put out fires.|Firefighters put out fires. Phrasal verb: put out fires.
Người làm vườn|Gardeners
Người làm vườn làm gì ở công viên?|What does a gardener do in the park?
Trồng cây trong công viên công cộng.|Plant trees in the public park.
Giao thông xanh|Green transport
Vì sao mọi người đi xe buýt?|Why do people take the bus?
Để giảm lượng xe lưu thông — reduce traffic.|To reduce traffic.
Ngày Chủ nhật|Sundays
Khi nào học sinh dọn dẹp công viên?|When do students clean the park?
Vào mỗi Chủ nhật. Every Sunday diễn tả một hoạt động lặp lại.|Every Sunday. This describes a repeated activity.
Từ vựng cộng đồng|Community vocabulary
Local community nghĩa là gì?|What does local community mean?
Cộng đồng địa phương: những người cùng sinh sống trong một khu vực.|A local community is a group of people living in the same area.
Một cộng đồng tốt đẹp bắt đầu từ những việc nhỏ. Cùng học cách gọi tên những người giúp ích cho nơi mình sống và kể về công việc của họ bằng tiếng Anh.|A strong community starts with small acts. Learn the English names of the people who help your neighbourhood and describe what they do.
Volunteer: tình nguyện viên giúp đỡ hàng xóm.|Volunteer: someone who helps their neighbours.
Library: thư viện cho mượn sách miễn phí.|Library: a place that lends books for free.
Firefighter: lính cứu hỏa dập lửa.|Firefighter: someone who puts out fires.
Đi xe buýt và dọn công viên là những việc làm cho cộng đồng.|Taking the bus and cleaning the park are ways to help the community.
Khách du lịch|Tourists
Người bán vé|Ticket sellers
Phi công|Pilots
Volunteers là các tình nguyện viên.|Volunteers are people who offer to help others.
Thư viện cho mượn sách như thế nào?|How does the library lend books?
Chỉ vào Chủ nhật|Only on Sundays
Miễn phí|For free
Chỉ cho giáo viên|Only to teachers
Với giá rất cao|At a very high price
For free nghĩa là miễn phí.|For free means at no cost.
Put out fires là công việc của ai?|Whose job is it to put out fires?
Học sinh|Students
Tài xế|Drivers
A firefighter puts out fires: lính cứu hỏa dập lửa.|A firefighter's job is to put out fires.
Tại sao mọi người đi xe buýt?|Why do people take the bus?
Để thi đấu|To compete
Để trồng cây|To plant trees
Để mượn sách|To borrow books
Để giảm lượng xe lưu thông|To reduce traffic
To reduce traffic nêu mục đích của việc đi xe buýt.|To reduce traffic explains the purpose of taking the bus.
Học sinh dọn công viên vào ngày nào?|On which day do students clean the park?
Mỗi Chủ nhật|Every Sunday
Mỗi thứ Hai|Every Monday
Mỗi thứ Sáu|Every Friday
Mỗi thứ Bảy|Every Saturday
Every Sunday nghĩa là mỗi Chủ nhật.|Every Sunday means on Sunday each week.
% trung bình|% average
nguồn mẫu|sample source
Mở góc học tập|Open study space
Đọc và nối các ý tưởng|Read and connect ideas
Cập nhật tác vụ đang chạy|Refresh running tasks
`.trim().split("\n").map(line => line.split("|")));

let uiLanguage = "vi";
try { uiLanguage = localStorage.getItem("padayon-ui-language") === "en" ? "en" : "vi"; } catch {}
const uiOriginals = new WeakMap();
const uiAttributes = new WeakMap();
const uiNormalize = text => text.replace(/\s+/g, " ").trim();
function t(text) {
  if (uiLanguage !== "en" || typeof text !== "string") return text;
  const key = uiNormalize(text);
  if (Object.hasOwn(UI_EN, key)) return text.replace(text.trim(), UI_EN[key]);
  if (key.includes(" · ") && key.split(" · ").every(part => Object.hasOwn(UI_EN, part)))
    return key.split(" · ").map(part => UI_EN[part]).join(" · ");
  if (key.includes(" — ") && key.split(" — ").every(part => Object.hasOwn(UI_EN, part)))
    return key.split(" — ").map(part => UI_EN[part]).join(" — ");
  const patterns = [
    [/^(\d+) câu · (\d+) câu đã phân loại$/, "$1 questions · $2 classified"],
    [/^01 · Trích xuất: (.+) câu$/, "01 · Extraction: $1 questions"],
    [/^02 · AI phân loại: (.+) câu$/, "02 · AI classification: $1 questions"],
    [/^03 · Phân tích kết quả: (.+)$/, (_, status) => "03 · Results analysis: " + t(status)],
    [/^Điểm tạm tính: (.+)$/, "Provisional score: $1"],
    [/^(\d+) câu chưa có đáp án để chấm · (\d+) câu trong đề$/, "$1 ungraded questions · $2 questions in the exam"],
    [/^Đã chọn (.+) câu$/, "$1 questions answered"],
    [/^Kết quả: (.+) câu đúng$/, "Result: $1 correct"],
    [/^(\d+ \/ \d+) câu đúng$/, "$1 correct"],
    [/^Câu (\d+–\d+)$/, "Questions $1"],
    [/^Câu (\d+)\. Chọn đáp án theo đoạn đọc\/hướng dẫn phía trên\.$/, "Question $1. Choose an answer using the passage/instructions above."],
    [/^Câu (\d+)(.*)$/, "Question $1$2"],
    [/^(\d+) ký tự đã xác nhận\.$/, "$1 characters confirmed."],
    [/^(\d+) lượt đang hiển thị · tối đa 100 lượt gần nhất\.$/, "$1 turns shown · up to the latest 100 turns."],
    [/^1 đoạn nguồn · (\d+) trang học · Cứ tò mò, cứ khám phá\.$/, "1 source passage · $1 learning pages · Stay curious. Keep exploring."],
    [/^Tìm hiểu “(.+)”$/, "Explore “$1”"],
    [/^CÂU (.+) · (\d+) CÂU ĐÃ CHỌN$/, "QUESTION $1 · $2 ANSWERED"],
    [/^TRANG (\d+)$/, "PAGE $1"],
    [/^Mở trang · (\d+)$/, "Open page · $1"],
    [/^Đến câu (\d+)$/, "Go to question $1"],
    [/^Mở trang (.+)$/, "Open page $1"],
    [/^(\d+) lượt làm bài$/, "$1 attempts"],
    [/^(\d+) lượt$/, "$1 attempts"],
    [/^Nguồn: (.+)$/, "Source: $1"],
    [/^Cập nhật: (.+)$/, "Updated: $1"],
    [/^Local dự phòng · (.+)$/, "Local fallback · $1"],
    [/^(.+) · Nội dung chưa qua giáo viên kiểm duyệt$/, (_, model) => model.replace(" · đang dùng local dự phòng", " · local fallback") + " · Not reviewed by a teacher"],
    [/^(\d+) \/ (✓ HOÀN TẤT|CHƯA HOÀN TẤT|CHỜ \/ XỬ LÝ)$/, (_, n, state) => n + " / " + ({"✓ HOÀN TẤT":"✓ COMPLETE","CHƯA HOÀN TẤT":"INCOMPLETE","CHỜ / XỬ LÝ":"QUEUED / PROCESSING"})[state]],
  ];
  for (const [pattern, replacement] of patterns)
    if (pattern.test(key)) return text.replace(text.trim(), key.replace(pattern, replacement));
  return text;
}
function translateUI(scope = document.body) {
  const excluded = 'script, style, [translate="no"], [contenteditable="true"]';
  if (scope.nodeType !== Node.ELEMENT_NODE || scope.closest(excluded)) return;
  const nodes = document.createTreeWalker(scope, NodeFilter.SHOW_TEXT);
  while (nodes.nextNode()) {
    const node = nodes.currentNode;
    if (node.parentElement.closest(excluded + ', textarea')) continue;
    const previous = uiOriginals.get(node);
    const source = previous && node.data === previous.rendered ? previous.source : node.data;
    const rendered = t(source);
    if (node.data !== rendered) node.data = rendered;
    uiOriginals.set(node, { source, rendered });
  }
  for (const element of [scope, ...scope.querySelectorAll('[placeholder], [aria-label], [title]')]) {
    if (element.closest(excluded)) continue;
    const records = uiAttributes.get(element) || {};
    for (const attribute of ["placeholder", "aria-label", "title"]) {
      if (!element.hasAttribute(attribute)) continue;
      const value = element.getAttribute(attribute), previous = records[attribute];
      const source = previous && value === previous.rendered ? previous.source : value;
      const rendered = t(source);
      if (value !== rendered) element.setAttribute(attribute, rendered);
      records[attribute] = { source, rendered };
    }
    uiAttributes.set(element, records);
  }
}
function setUILanguage(language) {
  uiLanguage = language === "en" ? "en" : "vi";
  try { localStorage.setItem("padayon-ui-language", uiLanguage); } catch {}
  document.documentElement.lang = uiLanguage;
  document.title = uiLanguage === "en" ? "BlueStudy · Your notebook of knowledge" : "BlueStudy · Cuốn vở tri thức của bạn";
  document.querySelectorAll("[data-language]").forEach(button => {
    button.setAttribute("aria-pressed", String(button.dataset.language === uiLanguage));
  });
  translateUI();
}
document.querySelectorAll("[data-language]").forEach(button => {
  button.addEventListener("click", () => setUILanguage(button.dataset.language));
});
// Translate incremental rendering without reloading or losing drafts / quiz choices.
const uiObserver = new MutationObserver(records => {
  uiObserver.disconnect();
  const scopes = new Set();
  for (const record of records) {
    const scope = record.target.nodeType === Node.TEXT_NODE ? record.target.parentElement : record.target;
    if (scope?.isConnected) scopes.add(scope);
  }
  for (const scope of scopes) translateUI(scope);
  observeUI();
});
function observeUI() {
  uiObserver.observe(document.body, {subtree:true, childList:true, characterData:true, attributes:true, attributeFilter:["placeholder", "aria-label", "title"]});
}
setUILanguage(uiLanguage);
observeUI();
