"""Private local object store, used by the single-machine MVP."""
from pathlib import Path
from uuid import UUID


class LocalStorage:
    def __init__(self, root: Path):
        self.root = root.resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def path(self, key: str) -> Path:
        # Keys are generated by the server, never filenames supplied by clients.
        stem, suffix = Path(key).stem, Path(key).suffix
        if suffix not in {'.txt', '.png', '.jpg', '.pdf'} or str(UUID(stem)) != stem:
            raise ValueError('Invalid storage key')
        path = (self.root / key).resolve()
        if path.parent != self.root:
            raise ValueError('Storage path escapes root')
        return path

    def put(self, key: str, content: bytes):
        with self.path(key).open('xb') as file:
            file.write(content)

    def read(self, key: str) -> bytes:
        return self.path(key).read_bytes()

    def delete(self, key: str):
        self.path(key).unlink(missing_ok=True)
